input("you wake up from a dream of eating mice. this draws you outside")
fightgray = input("you go into the forest until... YOU ARE ATTACKED!!!!!!!!!! do you fight? (y/n)")
if fightgray == "yes": input("you fight him and almost win.")
else: input("you lose but will keep going so lets just say you won")
input("he says you put up a good fight and that his name is graystripe")
input("he tells you its dangerous in the woods and that he's an apprentice warrior for thunderclan")
input("he tells you of four clans, thunderclan, riverclan, windclan, and shadowclan untill..")
input("more cats come two to be exact. they tell you they are bluestar and lionheart")
jointhunder = input("bluestar says you may be able to join thunderclan. do you accept? (y/n)")
if jointhunder == "yes": print("you join thunderclan")
else: print("yawwwwwwwwwwwwwwwwwwwwwwwwwwwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn")
input("they lead you to the woods the next morning. they have an area split up into parts")
input("bluestar says out to all of thunderclan that you are worthy as an apprentice until...")
fightlong = input("another thunderclan cat attacks you!!! he calls you a kittypet. do you attack? (y/n)")
if fightlong == "yes": print("you fight him valiantly but he rips off your collar. you are now a member, of thunderclan, your name is firepaw.")
else: print("well you die but you must keep goin!!!!!! he rips off your collar easily and you become a member of thunderclan.")
input("soon as you know, a cat runs up to bluestar. Redstripe, one of the deputies of thunderclan, has been killed.")
input("tigerclaw, a warrior said that oakheart, the deputy of riverclan, killed redtail. He also says that he killed oakheart.")
input("bluestar says a new deputy will be named tonight")
input("graystripe tells you of starclan. once a cat dies, they become a star of starclan.")
input("an injured warrior named ravenpaw lies on the ground. as a medicine cat, named spottedleaf comes to heal him")
input("tigerclaw asks if he will live, spottedleaf says he will.")
input("tigerclaw asks graystripe who you are, graystripe says that your name is firepaw")
input("you go to fourtrees, where all clans meet and discuss the new deputy, it will be lionheart!")
print("you go back to thundercamp and sleep")
input("the next day you go on patrol of thunderclan territory with multiple apprentices and tigerclaw and lionheart")
input("you are taught how to hunt! and are told to go get one piece of prey")
stalkpounce1 = input("you see a mouse, do you stalk slowly or pounce? (stalk/pounce)")
if stalkpounce1 == "stalk": print("you got the mouse!!!!!!")
else: print("well you didnt get the mice but tigerclaw is going to turn your head into a triangle if you dont get one so you find another")
input("you go back to tigerclaw and lionheart with the mice!")
input("lionheart tells you to eat with the elders. you eat your own mouse. you are very pleased")
input("over the next few moons, you train very hard to become a warrior. You will become a warrior!!!!!!!!")
input("you are told to go get herbs for spottedleaf from lionheart.")
input("she congratulates you on training so hard.")
input("the next day you go on tigerclaws hunting assesment. you are told to go to the twoleg place woods.")
input("tigerclaw will be watching you all.")
stalkpounce2 = input("while you are walking, you see a bird!! do you stalk slowly, or pounce? (stalk/pounce)")
if stalkpounce2 == "stalk": print("you caught the bird!")
else: print("erm??????????? well you uhh didnt get the bird")
input("later while walking you smell a cat you used to live with!!!!!! her name is princess")
input("she said she and another cat you used to live with named smudge were worrying about you")
input("she says you were scrawny and well... that isnt not true...")
input("you tell her that you are a warrior now and you share tounges for the last time.")
input("you go back to base and bluestar calls you.")
input("she asks you about your loyalty, and how you shared tounges with princess")
staythunder = input("she asks you if you want to stay in thunderclan. do you stay? (y/n)")
if staythunder == "yes": print("you will stay loyal to thunderclan.")
else: print("sigh... you made a dumb descision. like why did you do that bro??? well whatever. thx!")
print("Tysm for playing my text adventure!!!!!!! i hope you enjoyed it!")